# rule identifiers to exclude from running
disabled_rules:
  - trailing_whitespace
  - todo

# some rules are only opt-in
opt_in_rules:
  - empty_count
  - force_unwrapping

# paths to ignore during linting. Takes precedence over `included`.
excluded:
  - Carthage
  - Pods
  - Session/Session/Code/Constants/SwiftGen

line_length:
  warning: 200
  error: 250
